### PR TITLE
Add Makefile to dependency list.

### PR DESCRIPTION
**Pull request by user202729**
So that the program rebuilds when compiler flags are changed.

See https://stackoverflow.com/a/29877659 for more details.

### CODE REVIEW

**Comment by LBPHacker** [comment]
Well, I don't have that in there because you're not expected to change
build flags often enough to warrant having the Makefile listed as a
dependency. But I can add it if you think it's worth it.

**Comment by user202729** [comment]
Just a minor thing. Sometimes I edit the flags to debug etc. (there is `-O2`, `-g`, `-g -pg -fprofile-arcs -ftest-coverage`)

There is not really anything else to add (actually there is. Move non-model parts from `model.lua` (breakpoint etc.) to the emulator to improve performance. Watchlist. `unordered_map` instead of `map`... I tested this and the CPU usage doesn't reduce much.)

**Comment by LBPHacker** [comment]
Having `unordered_map` instead of `map` shoulnd't help too much, yeah, as I didn't use `map` in any hot code path. It's basically only used for storing command line arguments and register proxies. CPU.cpp does traverse `register_proxies` once but that's an O(n) thing.

**Comment by user202729** [comment]
Actually... the main loop calls post_tick for every tick, post_tick (implemented in Lua) calls cpu.pc (and csr), cpu.pc looks up the string "pc" in the map.

**Comment by LBPHacker** [comment]
Oh right... Oh well, that's a small map. I'm pretty sure invoking `post_tick` itself has a bigger impact than that lookup. Maps are nice because at loads like these (having a few registers or breakpoints in them) they provide almost constant time lookup.

**Pull request merged**
